### ISSUE TITLE
First time using and the PSPlexConfig.json file is created but empty.

### ISSUE THREAD

**Issue by 2wheelsnz** [robinmalik/PSPlex#16]
Just installed under PS 7.2.18 and ran the set-plexconfiguration.  No errors and the PSPlexConfig.json file is created but only contains [ ]

I then installed in PS 5.1 and tried again and same thing.  I had removed the config file first before trying within this PS version.

If during the set-plexconfiguration I supply (deliberately) the wrong server name I get an error so this tells me it is happy with the username and password.

Any thoughts on what could be wrong?  
Cheers
Barry

**Comment by robinmalik** [comment]
Hey Barry, thanks for the feedback and sorry you're having issues! I'm out for most of the day today, but I'll look into this tonight 🤓

**Comment by 2wheelsnz** [comment]
Thanks for the quick response.  No hurry.  My wife just happened to ask if I could generate a list of our movies that we had not watched, and Google took me to your PS module for Plex.  Awesome.
I tried again to set the plexconfiguration again just now with the -verbose flag, and it just outputted the following...

`VERBOSE: POST with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json`

Not sure if that helps... 
Cheers

**Comment by robinmalik** [comment]
@2wheelsnz Hi, apologies for not managing to look at this last night.

I've just tried deleting my `PSPlexConfig.json` and re-running `Set-PlexConfiguration` - the file contains expected data and `Get-PlexUser` works, so I can't replicate this issue just yet. I also get the same as you under PowerShell 5.1 regarding verbose output, so no thread to pull there, I don't think.

I have an inkling of where the problem might be (essentially an empty array being converted to JSON and then to file on disk) but we'll need to do some debugging.

You can try running some of the code from within the function itself. Here we go:

```powershell
$Credential = Get-Credential
$Base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $Credential.GetNetworkCredential().UserName, $Credential.GetNetworkCredential().Password)))
$Data = Invoke-RestMethod -Uri "https://plex.tv/users/sign_in.json" -Method POST -Headers @{
	'Authorization'            = ("Basic {0}" -f $Base64AuthInfo);
	'X-Plex-Client-Identifier' = "PowerShell-Test";
	'X-Plex-Product'           = 'PowerShell-Test';
	'X-Plex-Version'           = "V0.01";
	'X-Plex-Username'          = $Credential.GetNetworkCredential().UserName;
} -ErrorAction Stop
$ResourceData = Invoke-RestMethod -Uri "https://plex.tv/api/v2/resources?includeHttps=1&X-Plex-Token=$($Data.user.authentication_token)&X-Plex-Client-Identifier=PSPlex" -Method GET -UseBasicParsing -Headers @{"Accept" = "application/json, text/plain, */*" }
```

In `$ResourceData` should be a list of servers that you have access to, that are "online", whether you own them, other information, along with their `connection` details under a .connections property. You can echo this out and inspect it.

We currently refine the list of servers to only those you own, that have a public IP address which suggests it being remotely avaialble, *and* a "plexdirect" address that we use to communicate with the server.

I wonder - is this a locally hosted Plex instance (e.g. on a local LAN with a non-public IP), and that has remote access turned off?

Cheers

**Comment by 2wheelsnz** [comment]
Hi Robin,

That will be it.  It is a local instance with no remote access.

I'll temporarily setup remote access to con firm it works but otherwise I have no reason to leave remote access enabled.

Many thanks for following up.😀
Kind regards
Barry


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robinmalik** [comment]
Hey Barry, clearly it's not really acceptable to have to open up your Plex instance to use this module. I think the reason the module is using the plex direct URL (which requires public access) was 1) for simplicity and 2) to ensure communication was over https. I'll try and have a think about how to get localhost access integrated into how it's currently working.

**Comment by 2wheelsnz** [comment]
Thanks Robin.

 

I opened the ports and can confirm that the PSPlex module now creates the json file just fine.

 

I get an “Unable to connect to the remote server” but this will be something to do with my PFSense firewall config.  Plex says that remote access is now available.

 

Would be very interested if it were possible to use the modules without having to provide remote access at some point in time.

 

Many thanks for your time with this.  Happy for you to close the GitHub issue.

 

Kind regards

Barry

**Comment by robinmalik** [comment]
@2wheelsnz Give the new version a go - I've tweaked the internals so that if a server is found that doesn't have a public IP address it should be stored in `PSPlexConfig.json` using the private IP address. You'll need to re-run the `Set-PlexConfiguration` function and reopen PowerShell. Works for me with a private Plex instance. Fingers crossed!

**Comment by 2wheelsnz** [comment]
Hi Robin

 

I can confirm that this is working as you have stated.

 

Thank you so much for making that change to your Plex PowerShell module.

 

Kind regards

Barry
