### ISSUE TITLE
Support accounts with 2FA/MFA

### ISSUE THREAD

**Issue by robinmalik** [robinmalik/PSPlex#4]
This requires investigation and documenting (even if not possible).

**Comment by noaht8um** [comment]
Just wanted to jump in and say that you can use MFA if you append the 6-digit code to the end of your password when authenticating. I don't know if this is supported, intentional, etc. but it does work for me.

**Comment by robinmalik** [comment]
Thanks @noaht8um, I've added this to the README.md :)
