### ISSUE TITLE
Get-PlexPlaylist throwing error

### ISSUE THREAD

**Issue by go2tom42** [robinmalik/PSPlex#4]
OS: Windows 10
Powershell Version: 7.1.4
Plex Server Version: 1.29.1.6316

Get-PlexAuthenticationToken, Save-PlexConfiguration, Get-PlexUser, Get-PlexLibrary all function correctly

Plex server runs on a NUC running Ubuntu Server 20.04 LTS

`Get-PlexPlaylist
InvalidOperation: C:\Program Files\WindowsPowerShell\Modules\PSPlex\1.0.4\Public\Get-PlexPlaylist.ps1:94
Line |
  94 |  … ForEach-Object { $_.psobject.TypeNames.Insert(0, "PSPlex.Playlist") }
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.`

**Comment by robinmalik** [comment]
Thanks for raising this! I'll take a look later this evening after work :)

**Comment by go2tom42** [comment]
Get-PlexUser was not grabbing the token for Home Users

I added 
`$UserTokens | Where-Object { $_.username -eq "" } | ForEach-Object {$_.username = $_.title }`  

after  

`$UserTokens = Get-PlexUserToken -MachineIdentifier $PlexServer.machineIdentifier -ErrorAction Stop`

That seems to have fixed the issue

**Comment by robinmalik** [comment]
@go2tom42 Thanks, I've just added the fix to development and will get it onto the PS Gallery later as v1.0.5.

**Comment by go2tom42** [comment]
with 1.0.5 installed

```
UnInstall-Module -Name PSPlex
Install-Module -Name PSPlex
```


`$User = Get-PlexUser -User $username -IncludeToken`

Doesn't set $User.token

Replaced v1.0.5 module's Get-PlexUser.ps1 with v1.0.4 file with extra line from above and $User.token gets set

**Comment by robinmalik** [comment]
@go2tom42 Thanks for raising. Possibly a $null vs "" issue (it worked for me in the console yesterday but didn't run in totality). Will check.
