### ISSUE TITLE
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by pmwhelan** [robinmalik/PSPlex#5]
Hi

One command doesn't work and another does?

Thanks

P

PS C:\WINDOWS\system32> Get-PlexLibrary | Select title,type,key

Invoke-RestMethod : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

At C:\Program Files\WindowsPowerShell\Modules\PSPlex\1.0.12\Public\Get-PlexLibrary.ps1:48 char:18

+ [array]$Data = Invoke-RestMethod -Uri $DataUri -Method GET

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException

+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

PS C:\WINDOWS\system32> Get-PlexUser

title username email id allowSync

----- -------- ----- -- ---------

John John 25216963 1

Jim Jim 25217143 1

Grandad Grandad 28053843 0

PS C:\WINDOWS\system32>

**Comment by robinmalik** [comment]
Hi, thanks for raising this! I'll take a look tomorrow and once I've figured it out, push a fix in v1.0.13 with a few other things I've got ready to go.

**Comment by robinmalik** [comment]
Hi, thanks for raising this! I'll take a look tomorrow and once I've figured it out, push a fix in v1.0.13 with a few other things I've got ready to go.

**Comment by pmwhelan** [comment]
Thanks. Well done on putting this together. I think I will get a LOT of use out of it :)

**Comment by robinmalik** [comment]
Ok first, I can't replicate this on my side with either PowerShell 7 or 5.1 on Windows 11, or PowerShell 7 in Debian so it's nothing obviously broken (like me writing poor code 😁). 

Essentially it outputs as you might hope for:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/8790561/216052259-9342637b-6e69-4138-a2dc-56d7b0baab80.png">

The error `Could not establish trust relationship for the SSL/TLS secure channel.` is telling though. I don't have an SSL certificate on my Plex server. Do you? Are you able to check:

1. That it's still valid 
2. That it's trusted (at least by your browser, we can start with that)

Edit: The reason `Get-PlexUser` works is because it doesn't actually query your server for that, but makes a request direct to `https://plex.tv/api/users` so doesn't actually hit your Plex server.

**Comment by pmwhelan** [comment]
Hi Robin

Thanks for taking the time.

I'm not really sure.

Does this help?

Thanks
P

[image: image.png]

[image: image.png]

**Comment by robinmalik** [comment]
@pmwhelan No worries :) Unfortunately it looked like the reply via email didn't attach the images.

**Comment by pmwhelan** [comment]
![image](https://user-images.githubusercontent.com/75440573/216062040-c19df280-0140-4307-b641-4b8ee6925e83.png)

![image](https://user-images.githubusercontent.com/75440573/216062158-28146285-0766-42ac-86a2-427630811173.png)

**Comment by pmwhelan** [comment]
Let me know if you can see those two images. thanks

**Comment by robinmalik** [comment]
They're there now :) Ok so check the following for me:
`C:\Users\USERNAME\AppData\Roaming\PSPlex\PSPlexConfig.json`

Against `PlexServerHostname` does it say `app.plex.tv` or is it the hostname of your actual server? 

EDIT: And is the protocol `https`? What is set for `port`?

I've not actually tried direct queries to app.plex.tv... 🤔

**Comment by pmwhelan** [comment]
Here are the details.
Yes that is 69 in my IP address :)

[
    {
        "Username":  "myusername",
        "Token":  "lots of text",
        "PlexServer":  "servername",
        "PlexServerHostname":  "192.168.1.69",
        "Protocol":  "https",
        "Port":  32400,
        "Default":  true
    }
]

**Comment by pmwhelan** [comment]
@robinmalik I see under my Plex server I have a Public and Private URL
I have changed Save-PlexConfiguration to use the Public URL and now I get ...

PS C:\WINDOWS\system32> Get-PlexLibrary | Select title,type,key
Invoke-RestMethod : Unable to connect to the remote server

![image](https://user-images.githubusercontent.com/75440573/216080309-26bbf0e9-016f-4e0e-9cfc-f008b39ba3c1.png)

**Comment by robinmalik** [comment]
I'm just spinning up a local Plex server on 192.x.x.x to try testing with :)

**Comment by robinmalik** [comment]
Ok from my local network with the following config:

```
[
  {
    "Username": "REMOVED",
    "Token": "REMOVED",
    "PlexServer": "HomeDesktop",
    "PlexServerHostname": "192.168.0.20",
    "Protocol": "http",
    "Port": 32400,
    "Default": true
  }
]
```

This works:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/8790561/216081762-fc75abd7-b50d-481e-a65d-dd67c390f5b4.png">

If I change this to `https` I get the same as your original post (`The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.`) which makes sense. 

The first thing I'd try is reverting to using a local IP address (so the private IP starting with 192) and change the protocol to `http`. If this works, you're in the same position as me. This assumes of course that you're on the same local network as your Plex server right now :)

We can then figure out how best to get this working using `https`.

**Comment by pmwhelan** [comment]
@robinmalik 
Thanks once again.
Check it out (first attempt is with http the second is with https) ...
![image](https://user-images.githubusercontent.com/75440573/216083548-d6d1526c-35f6-4b06-bea8-84eb916d9768.png)

**Comment by robinmalik** [comment]
You've found a bug that's been annoying me for a while 👀 A fix for that is coming in the next version. 

For now if you find yourself having to run `Get-PlexAuthenticationToken` and `Save-PlexConfiguration` then for the latter command add `-Default` on the end and it should avoid the error.

**Comment by pmwhelan** [comment]
You got it!
That worked. 
You are a star.
Now to see if I can get a script to look through an Excel file and add all movie entries to a collection :)
Thanks again.

**Comment by robinmalik** [comment]
At the moment, the module doesn't support adding items to collections, only playlists, but I have started work on a function for adding to collections.

For working with Excel, check out [ImportExcel](https://github.com/dfinke/ImportExcel) - certainly one of the best PowerShell modules around. 

Ultimately a script to do what you're wanting might look something like this:

```powershell
$Excel = Import-Excel -Path "c:\movies.xlsx"
foreach($Movie in $Excel)
{
  # Assumes the Excel has a column called Title
  $Item = Find-PlexItem -ItemName $Movie.Title
  if($Item -and $Item.count -eq 1)
  {
    # We're very much assuming an accurate match based on title here and it might not be the case
    # Add plex item to collection...
  }
}
```

I'll keep this issue open for now as I want to look into the SSL side of things and make sure we can support that.

**Comment by pmwhelan** [comment]
Thanks again

I might be having a brain-fart but ...

$Item = Find-PlexItem -ItemName "Goodfellas"

  write-host "Item.count:" $Item.Count
  if($Item -and $Item.count -eq 1)
  {
    write-host "Item.Title:" $Item.Title
    
  }

This gives me 0 even though I do have Goodfellas.

And if I search for Heat I get 15 results even though the only two suggested in Plex are Heat and The Heat.

I realise Im getting off topic!

Thanks
P

**Comment by robinmalik** [comment]
🤔 It appears to work for me:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/8790561/216095227-545cced4-4bd8-47e4-899c-8dc717bb0071.png">

I'd probably have to look at the code for `Find-PlexItem` to dig deeper - it was written a while ago and tried to replicate the behaviour from the web interface but Plex have adjusted that over time.

By default it queries your entire Plex server and not a single library. It supports refining results by `-LibraryTitle` so if your films are in a single library, you can try that. You can even try adding `-ItemType movie` (if you're not specifying a library and wanting to search across multiple libraries, I think...).

I wonder why you've got 15 results and then only two when searching via the web 🤔 Could it be that the web search is restricted to a certain type, like only film and programmes?:

<img width="164" alt="image" src="https://user-images.githubusercontent.com/8790561/216096674-64656603-eee3-4e1e-a5c8-665065f197ac.png">

**Comment by pmwhelan** [comment]
Web Plex is searching in "All Media Types"
$Item = Find-PlexItem -ItemName "Heat" -LibraryTitle "Films"
PS C:\WINDOWS\system32> C:\downloads\complete\getMovies.ps1
Item.count: 2

$Item = Find-PlexItem -ItemName "Goodfellas" -LibraryTitle "Films"
PS C:\WINDOWS\system32> C:\downloads\complete\getMovies.ps1
Item.count: 

It's actually just blank. Not 0.

**Comment by pmwhelan** [comment]
Same with ItemType ...

$Item = Find-PlexItem -ItemName "Goodfellas" -ItemType movie

  write-host "Item.count:" $Item.Count

PS C:\WINDOWS\system32> C:\downloads\complete\getMovies.ps1
Item.count: 

$Item = Find-PlexItem -ItemName "Heat" -ItemType movie

  write-host "Item.count:" $Item.Count


PS C:\WINDOWS\system32> C:\downloads\complete\getMovies.ps1
Item.count: 2

**Comment by robinmalik** [comment]
If you do this, is Goodfellas in the list?

```powershell
$Films = Get-PlexItem -LibraryTitle 'Films'
$Films | Sort title | Select title,year,ratingKey
```

If it is, then run `Get-PlexItem -Id <ratingKey>` with the rating key explicitly for Goodfellas and see if that's working.

**Comment by pmwhelan** [comment]
Yes it got it that way! 
Any idea why the other way doesn't work?


$Films = Get-PlexItem -LibraryTitle 'Films'
$Films | Sort title | Select title,year,ratingKey

exit

$Film = Get-PlexItem -Id 6638
write-host $Film.title

 exit

**Comment by robinmalik** [comment]
Nothing off the top of my head (especially as it's working for me) but it's been a long time since I last looked at how Plex constructs searches. I'll have a look once I've finished the current set of modifications.

**Comment by pmwhelan** [comment]
Thanks again.
It's a fantastic resource.
I'll try to direct people to it.

**Comment by robinmalik** [comment]
@pmwhelan FYI I'm going to be releasing 1.0.13 this weekend (hopefully), which involves changes to how the Plex config is stored and imported. I can't say that it'd fix your issue re: Goodfellas, but as the original SSL/TLS issue is no longer an issue I'm going to mark this as resolved. Please do open a new issue though if you have issues post upgrade to 1.0.13.
