### ISSUE TITLE
Consider using Plex.direct for API queries (rather than direct to server)

### ISSUE THREAD

**Issue by robinmalik** [robinmalik/PSPlex#6]
From the web client we can see that most requests for data are proxied by Plex over a secure URL comprised of IP address, some other identifier + `.plex.direct`. The SSL certificate backing this is provided by LetsEncrypt, and it's managed by Plex.

At the moment this module requires a user specify a direct hostname for their server, along with a protocol (http or https).

We could possibly make all lookups go via plex.direct instead, which would prevent the need to troubleshoot issues with user SSL certs (e.g. expired, not trusted, etc) and also mean that SSL is being used by default in the event that Plex servers are lacking their own certificate.

A downside to this approach is obviously that queries aren't going direct to server.

**Comment by trackd** [comment]
the .plex.direct is directly to the server?

the ip part of the plex.direct "192-168-10-100" will make it resolve to that IP

e.g 
192-168-10-100.(secrethash).plex.direct = 192.168.10.100
so queries will be sent directly to the server, they are not proxied.


atleast it's that way for me.

nslookup 192-168-1-100.(secret).plex.direct 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
Name:    192-168-1-100.(secret).plex.direct
Address:  192.168.1.100

i use it for all integrations/api calls with plex to be able to use https with real certificate & "Secure Connections = Required"

**Comment by robinmalik** [comment]
Hey @trackd, thanks for the reply here! You'd clearly picked up on me pondering but not accurately describing, whether traffic was being proxying through Plex. You'll be right though, I'm sure :)

I think I'm going to default to using the plex.direct approach and have started work on supporting this. I just need to find a moment to finish it :) You can obtain that 'secrethash' from the Plex API thankfully - I'm just hoping they don't change it often.
